### PR TITLE
Unidad2

### PR DESCRIPTION
**Pull request by armando0509**
Se subió el Examen Unidad 2 al repositorio de Datos Masivos

### CODE REVIEW

**Comment by jcromerohdz** [comment]
Nice work, but you need to do a README.md and explain your work, proceed with this change then send me the pull request again

**Comment by armando0509** [comment]
Ready, the review was done and a README.md of the work of Evaluation 3 was uploaded

**Comment by jcromerohdz** [comment]
Great work, but I see your README.md in Unidad 2 branch don't have a well format please fix this issue then send me the PR again in order to proceed with the Marge to master

**Comment by armando0509** [comment]
Ready was resolved in README.md in branch 2

**Comment by jcromerohdz** [comment]
Hi Armando, hey something wrong with the README.md I can not see anything please solve this problem in order to proceed with the Marge

**Pull request merged**
